spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${{secrets.AWS_RDB_URL}}
    username: root
    password: ${{secrets.AWS_DB_PASSWORD}}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

cloud:
  aws:
    credentials:
      access-key: ${{secrets.AWS_ACCESS_KEY}}
      secret-key: ${{secrets.AWS_SECRET_KEY}}
    region:
      static: us-east-1
    stack:
      auto: false

s3:
  bucket:
    name: ${{secrets.AWS_S3_NAME}}
    folder: survey/



