name: Call GitHub API

on: [push]

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p ./src/main/resources/
          echo "${{ secrets.PROPERTIES }}" > ./src/main/resources/application.properties
          cat ./src/main/resources/application.properties
          ls -la ./src/main/resources/

