name: Call GitHub API

on: [push]

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "${{secrets.PROPERTIES}}" >> ./src/main/resources/application.properties




