name: Call GitHub API

on: [push]

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pwd
          ls -la
          echo "${{ secrets.PROPERTIES }}" > ./src/main/resources/application.properties


