name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Setting Production Profile Properties
      env:
        PROD_APPLICATION_YML: ${{ secrets.PROD_APPLICATION_YML }}
        PROD_APPLICATION_YML_DIR: src/main/resources
        PROD_APPLICATION_YML_FILE_NAME: application-prod.yml
      run: echo $PROD_APPLICATION_YML | base64 --decode > $PROD_APPLICATION_YML_DIR/$PROD_APPLICATION_YML_FILE_NAME

    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dspring.profiles.active=prod

    - name : Upload Jar File to Instance Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_ID }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "target/*.jar"
        target: "~/"
        rm: false

    - name: Execute Shell Script Stop Server
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_ID }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script_stop: true
        script: "./shutup.sh"

    - name: Sleep for 60 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '60s'

    - name: Execute Shell Script Run Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_ID }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script_stop: true
        script: "./startup.sh"
